name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      # Needed for cargo-make
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo make
        run: cargo install cargo-make

      - name: get Sysbox
        run: wget https://downloads.nestybox.com/sysbox/releases/v0.6.1/sysbox-ce_0.6.1-0.linux_amd64.deb

      - name: Install Sysbox
        run: sudo apt-get install ./sysbox-ce_0.6.1-0.linux_amd64.deb

      - name: Configure Sysbox runtime
        run: sudo cp sysbox/daemon.json /etc/docker/daemon.json

      - name: Restart docker service
        run: sudo systemctl restart docker.service

      - name: Build docker
        run: cargo make docker-build

      - name: Run docker
        run: cargo make docker-run

      - name: Allow Docker image to boot up
        uses: juliangruber/sleep-action@v1
        with:
          time: 120s

      # Needed to run tests
      - name: Install npm dependencies
        run: cargo make deps-npm

      - name: Test
        run: cargo make test-app

      - name: Show logs
        run: cargo make docker-log

        # New steps added below for Docker push
      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker image
        if: github.ref == 'refs/heads/main'
        run: docker tag zsolangpg ahmadsamehh/zsolangpg:latest

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: docker push ahmadsamehh/zsolangpg:latest
